version: "3.7"
services:
  app-0:
    image: cv-app-0
    build:
      context: ./app-0
    ports:
      - 4001:4001

  app-1:
    image: cv-app-1
    build:
      context: ./app-1
    ports:
      - 4002:4002
