apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: node
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - name: cv-app-0
    port: 4001
    targetPort: 4001
    protocol: TCP
  - name: cv-app-1
    port: 4002
    targetPort: 4002
    protocol: TCP
